{% set version = "15.0.1" %}

package:
  name: coloredlogs
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/c/coloredlogs/coloredlogs-{{ version }}.tar.gz
  sha256: 7c991aa71a4577af2f82600d8f8f3a89f936baeaf9b50a9c197da014e5bf16b0

build:
  number: 3
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  entry_points:
    - coloredlogs = coloredlogs.cli:main

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - pip
    - humanfriendly >=9.1
  run:
    - python
    - humanfriendly >=9.1

test:
  imports:
    - coloredlogs
# Probably requires a valid TERM and a pager, it is hanging on our CIs.
#  commands:
#    - coloredlogs --help  # [not osx]

about:
  home: https://coloredlogs.readthedocs.org
  license: MIT
  license_file: LICENSE.txt
  summary: Colored terminal output for Python's logging module

extra:
  recipe-maintainers:
    - ocefpaf
    - andfoy
    - ccordoba12
