{% set version = "11.1" %}

package:
  name: coloredlogs
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/c/coloredlogs/coloredlogs-{{ version }}.tar.gz
  sha256: b82ea0f0d6d9562e2a893af278ed463b0cb77f48c8b2c76734040ef37078bcb2

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
  entry_points:
    - coloredlogs = coloredlogs.cli:main

requirements:
  build:
    - python
    - pip
    - humanfriendly >=4.7
  run:
    - python
    - humanfriendly >=4.7
    - colorama  # [win]

test:
  imports:
    - coloredlogs
# Probably requires a valid TERM and a pager, it is hanging on our CIs.
#  commands:
#    - coloredlogs --help  # [not osx]

about:
  home: https://coloredlogs.readthedocs.org
  license: MIT
  license_file: LICENSE.txt
  summary: Colored terminal output for Python's logging module

extra:
  recipe-maintainers:
    - ocefpaf
    - andfoy
    - ccordoba12
